// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://egrygbqemiwxfovsknmo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVncnlnYnFlbWl3eGZvdnNrbm1vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyMzQ2NzQsImV4cCI6MjA3MzgxMDY3NH0.xoDwzU3Jz8F6XgdFJnMepXWlgZRj-h-jbLNzDj-37Ag";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});